### PR TITLE
Upgrade plaid-ruby to 2.0

### PR DESCRIPTION
**Pull request by JCBarry**
Plaid-ruby upgrades to 2.0 has a bunch of breaking changes.  Upgrade will also make Stripe support possible.

### CODE REVIEW

**Comment by JCBarry** [comment]
this is in a holding pattern until the official 2.0 release of plaid-ruby

**Comment by jacobnbrum** [comment]
@JCBarry Hi, great gem. What is the status on this update?

**Comment by JCBarry** [comment]
Check out the 1.0beta branch and subsequent beta version of the gem -- it's where it landed, but I don't have a Stripe entitled Plaid account so that portion works only in theory.

Here ya go: https://rubygems.org/gems/argyle/versions/1.0.0.beta

**Comment by jacobnbrum** [comment]
Great! Thanks

**Pull request closed without merging**
